Review full project
MaksimPozharskiy/proxy-go pull request #2
Opened 2023-09-26 19:51 UTC by MaksimPozharskiy

2023-09-26 21:39 UTC, suzibill requested changes

2023-09-26 21:39 UTC, suzibill commented on proxy.go
> +			break
тут сразу return можно

2023-09-26 21:39 UTC, suzibill commented on proxy.go
> +	if err != nil {
а тут  return nil, err  без проверок

2023-09-26 21:39 UTC, suzibill commented on Dockerfile
> +FROM golang:latest
докерфайл можно улучшить сделав multistage building

2023-09-26 21:39 UTC, suzibill commented on metrics.go
> +package main
код не разбит на пакеты, все в мейне

2023-09-26 21:39 UTC, suzibill commented on metrics.go
> +    Addr: ":8090",
порты можно также в .env вынеси

2023-09-26 21:39 UTC, suzibill commented on proxy.go
> +		fmt.Println(err)
смешение fmt и log, можно slog использовать

2023-09-26 21:39 UTC, suzibill commented on main.go
> +	err := server.ListenAndServe()
нет graceful shutdown

2023-09-26 21:39 UTC, suzibill commented on proxy.go
> +	targetUrl := os.Getenv("PROXY_TARGET_URL") + fmt.Sprintf("%s", req.URL)
можно завести конфиг, в конфиг парсить .env и потом с этим конфигом работать, тут ты на каждый req дергаешь  os.Getenv

2023-09-27 13:11 UTC, asadkovich commented on metrics.go
> +)
Форматирование поехало, в редакторе можно поставить автоматическое форматирование при сохранени.
Также под скобки `var ()` и `const ()`  стоит группировать все переменные схожие по назначению:

```go
var (
    metricVar1 = 1
    mectricVar2 = 2
)

var (
    settingVar1 = "1"
    settingVar2 = "2"
)
```

2023-09-27 13:11 UTC, asadkovich commented on metrics.go
> +func startMetricsServer() *http.Server {
Нейминг функции тут можно улучшить, все таки ты не стартуешь сервер, а только создаешь

2023-09-27 13:11 UTC, asadkovich commented on proxy.go
> +func startProxyServer() *http.Server {
Опять нейминг не отражает назначение функции

2023-09-27 13:11 UTC, asadkovich commented on proxy.go
> +func startProxyServer() *http.Server {
Также схожий код для серверов при желании можно обернуть в свою абстракцию, вынести в отдельный пакет и передавать ему необходмые хендлеры и порт, чтобы переиспользовать в проекте.

Получится что-то вроде:

```go
metricsSrv := server.New(metricsHandlers, metricsPort)
proxySrv := server.New(proxyHandlers, proxyPort)

go metricsSrv.Run(ctx)
err := proxySrv.Run(ctx)
```

2023-09-27 13:11 UTC, asadkovich commented on readme_src/example.jpg
Лайфхак: если положить картинку в буфер обмена и нажать ctrl-v в редакторе markdawn на гитхабе, то гитхаб закинет картинку на свои сервера и вставит ее в документ)

2023-09-27 13:11 UTC, asadkovich commented on proxy.go
> +	writer.WriteHeader(resp.StatusCode)
Используешь то `resp.StatusCode`,  то `statusCode`. Стоит определиться, надо ли было вообще заводить новую переменную

2023-09-27 13:11 UTC, asadkovich commented on proxy.go
> +	}
Можно сократить до

```go
proxyReq.Header = req.Header.Copy()
```

2023-09-27 13:14 UTC, asadkovich commented on metrics.go
> +	prometheus.MustRegister(throughputHistogram)
у MustRegister перемннное число аргументов, поэтому вызов можно не дублировать и сделать

```go
prometheus.MustRegister(
    requestsTotal,
    responseTimeHistogram,
    httpStatusCount,
    throughputHistogram,
)
```

2023-10-08 16:52 UTC, MaksimPozharskiy commented on proxy.go
> +	}
proxyReq.Header = req.Header.Clone() скорее, у http.Header нет метода Copy

2023-10-30 14:11 UTC, merged